version: '3'

volumes:
    db_data:

services:
    db:
        image: mariadb:10.9
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: password

    php-fpm:
        build: ./docker/php-fpm
        volumes:
            - ./:/app
        working_dir: /app
        # Place UID=1000, GID=1000 in the .env
        user: $UID:$GID
        depends_on:
            - db

    php-cli:
        build: ./docker/php-cli
        volumes:
            - ./:/app
        working_dir: /app
        # Place UID=1000, GID=1000 in the .env
        user: $UID:$GID

    nginx:
        image: nginx:1.23
        ports:
            - 8080:80
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /app
        depends_on:
            - php-fpm
